---
## zetro-frontend image version
##

deployment:
  image:
    repository: /zetro-frontend
    pullPolicy: Always
  replicas: 1
  securityContext:
    enabled: true
  rolling:
    maxSurge: "25%"
    maxUnavailable: "25%"
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 1
      memory: 512M

service:
  port: 80
  targetPort: 8080

github: "ZeTro-dev/portfolio"
backendURL: "/api"

ingress:
  prefix: ""
  suffix: ""

config:
  LOGGER_NAME: zetro-frontend-logger
