apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "zetro-backend.fullname" $ }}
  labels:
    app: {{ template "zetro-backend.fullname" $ }}
    chart: {{ template "zetro-backend.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ include "zetro-backend.fullname" . }}-rewrite@kubernetescrd"
spec:
  tls:
    - hosts:
        - zetro.zelytra.fr
      secretName: zetro-zelytra-fr-tls
  ingressClassName: traefik
  rules:
    - host: "zetro.zelytra.fr"
      http:
        paths:
          - path: {{.Values.ingress.path | default "/api" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "zetro-backend.fullname" $ }}
                port:
                  number: {{.Values.service.port}}
