---
## zetro-backend image version
##

deployment:
  image:
    repository: /zetro-backend
    pullPolicy: Always
  replicas: 1
  securityContext:
    enabled: true
  rolling:
    maxSurge: "25%"
    maxUnavailable: "25%"
  resources:
    requests:
      cpu: 100m
      memory: 100M
    limits:
      cpu: 200m
      memory: 200M

service:
  port: 80
  targetPort: 8080

postgresql:
  enabled: true
  auth:
    existingSecret: "zetro-db-secret"
  primary:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      storageClass: "standard"  # or whatever is used in your cluster
      size: 50Mi

ingress:
  prefix: ""
  suffix: ""

config:
  LOGGER_NAME: zetro-backend-logger
