apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "zetro-frontend.fullname" $ }}
  labels:
    app: {{ template "zetro-frontend.fullname" $ }}
    chart: {{ template "zetro-frontend.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - zetro.zelytra.fr.fr
      secretName: zetro-zelytra-fr-tls
  ingressClassName: traefik
  rules:
    - host: "zetro.zelytra.fr.fr"
      http:
        paths:
          - path: {{.Values.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "zetro-frontend.fullname" $ }}
                port:
                  number: {{.Values.service.port}}
