apiVersion: v1
kind: Service
metadata:
  name: {{ template "zetro-frontend.fullname" . }}
  labels:
    app: {{ template "zetro-frontend.fullname" $ }}
    chart: {{ template "zetro-frontend.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
    platform: {{ .Values.global.config.PLATFORM }}
spec:
  ports:
    - name : http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "zetro-frontend.fullname" $ }}
    release: {{ .Release.Name }}