global:
  docker:
    # Artifactory host used for download Docker images
    artifactoryUrl: "zelytra"
    # Set in Gitlab-ci at the deployment. See values in CI/CD gitlab variables
    user: ""
    password: ""
    imageTag:
      zetroFrontend: latest
      zetroBackend: latest

  config:
    PLATFORM: dv1

postgresql:
  enabled: true
  auth:
    existingSecret: "zetro-db-secret"
  primary:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      storageClass: ""
      size: 100Mi